version: '3.8'

services:
  app:
    build: .
    container_name: scoring_app
    command: gunicorn --bind 0.0.0.0:5000 --workers 4 --timeout 120 app:app
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./ml_model:/app/ml_model
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_NAME=bankruptcy_scoring
      - DB_USER=scoring_user
      - DB_PASSWORD=secure_password
      - MOCK_MODE=${MOCK_MODE:-false}
      - PROXY_LIST=${PROXY_LIST:-}
      - LOG_LEVEL=INFO
      - CACHE_TTL=3600
      - CACHE_MAX_SIZE=1000
      - CHUNK_SIZE=10000
    depends_on:
      - db
    networks:
      - scoring_network

  db:
    image: postgres:13-alpine
    container_name: scoring_db
    environment:
      POSTGRES_DB: ${DB_NAME:-bankruptcy_scoring}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secure_password}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/migrations:/docker-entrypoint-initdb.d
    networks:
      - scoring_network
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: scoring_redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - scoring_network

networks:
  scoring_network:

volumes:
  pgdata:
  redisdata:
  